# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

AWSTemplateFormatVersion: 2010-09-09
Description: >-
    Tesseract OCR
Transform:
    - AWS::Serverless-2016-10-31
Globals:
    Function:
        Timeout: 5
        Runtime: nodejs12.x
        Environment:
            Variables:
                AWS: true
Resources:
    readImage:
        Type: AWS::Serverless::Function
        Properties:
            Handler: build/src/handlers/index.readImage
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: readImage
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /readImage
                        Method: POST
Outputs:
    WebEndpoint:
        Description: 'API Gateway endpoint URL for Sam Sample'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/tesseract-ocr/'
